version: '3.4'

services:
  consumerapi:
    image: ${DOCKER_REGISTRY-}consumerapi
    build:
      context: .
      dockerfile: ConsumerAPI/Dockerfile

  serviceapi:
    image: ${DOCKER_REGISTRY-}serviceapi
    build:
      context: .
      dockerfile: ServiceAPI/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672